project:
  type: website
  output-dir: docs

website:
  title: "BSC6926fall2023"
  navbar:
    left:
    - text: "Syllabus"
      href: sylb.html
    - text: "Computer setup"
      href: comp.html

format:
  html:
    theme: yeti
    highlight: haddock
    css: styles.css
    toc: false



