<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BSC6926fall2023 - Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BSC6926fall2023</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../sylb.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../comp.html" rel="" target="">
 <span class="menu-text">Computer setup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws1.html" rel="" target="">
 <span class="menu-text">WS 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws2.html" rel="" target="">
 <span class="menu-text">WS 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws3.html" rel="" target="">
 <span class="menu-text">WS 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws4.html" rel="" target="">
 <span class="menu-text">WS 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws5.html" rel="" target="">
 <span class="menu-text">WS 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws6.html" rel="" target="">
 <span class="menu-text">WS 6</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws7.html" rel="" target="">
 <span class="menu-text">WS 7</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws8.html" rel="" target="">
 <span class="menu-text">WS 8</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../ws9.html" rel="" target="">
 <span class="menu-text">WS 9</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../hw1.html" rel="" target="">
 <span class="menu-text">HW 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../hw2.html" rel="" target="">
 <span class="menu-text">HW 2</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#instructions" id="toc-instructions" class="nav-link active" data-scroll-target="#instructions">Instructions</a></li>
  <li><a href="#data-for-questions" id="toc-data-for-questions" class="nav-link" data-scroll-target="#data-for-questions">Data for questions</a>
  <ul class="collapse">
  <li><a href="#section-1-15-pts" id="toc-section-1-15-pts" class="nav-link" data-scroll-target="#section-1-15-pts">Section 1 (15 pts)</a></li>
  <li><a href="#section-2-23-pts" id="toc-section-2-23-pts" class="nav-link" data-scroll-target="#section-2-23-pts">Section 2 (23 pts)</a></li>
  <li><a href="#section-3-19-pts" id="toc-section-3-19-pts" class="nav-link" data-scroll-target="#section-3-19-pts">Section 3 (19 pts)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="instructions" class="level2">
<h2 class="anchored" data-anchor-id="instructions">Instructions</h2>
<p>Please, using quarto or rmarkdown, answer the questions below. You can use the class notes, the recommended books, and other web materials to help answer the questions. You can work on the homework in groups, but please independently submit pdf document containing answers and code.</p>
<p><strong>In two weeks (10/31/23 by 11:59pm)</strong>, please submit your pdf file to CANVAS using the following filename structure LastName_HW2_Filetype_Date (e.g., Santos_HW2_R_20230927). Again, you can share and work together on the code, but independently, submit your answers to the short answer questions in your own words and as markdown text under each question. Here are links to resources about <a href="https://r4ds.hadley.nz/quarto">quarto</a> and <a href="https://rmarkdown.rstudio.com/lesson-1.html">rmarkdown</a>.</p>
<p>Please reach out if you have any questions about the hw or how to make a pdf using quarto or rmarkdown.</p>
</section>
<section id="data-for-questions" class="level2">
<h2 class="anchored" data-anchor-id="data-for-questions">Data for questions</h2>
<p>For this section 1 and 2 of this homework, you will use a dataset from the <code>lterdatasampler</code> R package <a href="https://lter.github.io/lterdatasampler/" class="uri">https://lter.github.io/lterdatasampler/</a> called “and_vertebrates”. The <code>lterdatasampler</code> R package was created by the NSF LTER program <a href="https://lternet.edu" class="uri">https://lternet.edu</a> to provide data examples for educational purposes. This dataset consists of the populations of Coastal giant salamander (<em>Dicamptodon tenebrosus</em>) in two standard reaches of Mack Creek in the H.J. Andrews Experimental Forest that have been monitored since 1987. The two standard reaches are in a section of clear-cut forest (ca. 1963) and an upstream old-growth forest (&gt;500 years). Sub-reaches are sampled with 2-pass electrofishing, and all individuals are measured and weighed.</p>
<section id="section-1-15-pts" class="level3">
<h3 class="anchored" data-anchor-id="section-1-15-pts">Section 1 (15 pts)</h3>
<ol type="1">
<li>Upload “and_vertebrates” into R-Studio (remember you have to download the lterdatasampler R package before). Using R, create a new dataset by selecting only salamander data from the lower reach section, then calculate abundance (total number of individuals collected) by sitecode and year for Coastal giant salamander. Please, use “Nt” to name the column with the abundance data. Here are details about the “and_vertebrates” data useful to answer this question (look for info in the “Table Column Descriptions” tab in Data Entities - <a href="https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-and.4027.14" class="uri">https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-and.4027.14</a> (3 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lterdatasampler)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.3     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">'and_vertebrates'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> and_vertebrates <span class="sc">|&gt;</span>  </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species <span class="sc">==</span> <span class="st">'Coastal giant salamander'</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>         reach <span class="sc">==</span> <span class="st">'L'</span>) <span class="sc">|&gt;</span> </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year,sitecode) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Nt =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'year'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 54 × 3
# Groups:   year [27]
    year sitecode    Nt
   &lt;dbl&gt; &lt;chr&gt;    &lt;int&gt;
 1  1993 MACKCC-L    54
 2  1993 MACKOG-L    29
 3  1994 MACKCC-L    60
 4  1994 MACKOG-L    56
 5  1995 MACKCC-L    33
 6  1995 MACKOG-L    49
 7  1996 MACKCC-L    36
 8  1996 MACKOG-L    32
 9  1997 MACKCC-L    53
10  1997 MACKOG-L    37
# ℹ 44 more rows</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Plot annual estimates of salamander abundance per sitecode (2 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(year,Nt, <span class="at">color =</span> sitecode))<span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="3" type="1">
<li>Short Essay Question: How do the temporal trends of Coastal giant salamander between the sitecode compare (5 pts)?</li>
</ol>
<p><em>Overall the clear cut forest tends to support higher abundance of salamanders than the old growth site. Each populations tends to have fluctuations at similar times, but the old growth populations tends to be more stable. </em></p>
<ol start="4" type="1">
<li>Using R, calculate lambda from one year to the next (i.e., for each time step) for the two reach (sitecode) you selected. Try using either a for-loop or functions (1 pt).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sitecode) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lambda =</span> <span class="fu">lead</span>(Nt)<span class="sc">/</span>Nt)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 54 × 4
# Groups:   sitecode [2]
    year sitecode    Nt lambda
   &lt;dbl&gt; &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
 1  1993 MACKCC-L    54  1.11 
 2  1993 MACKOG-L    29  1.93 
 3  1994 MACKCC-L    60  0.55 
 4  1994 MACKOG-L    56  0.875
 5  1995 MACKCC-L    33  1.09 
 6  1995 MACKOG-L    49  0.653
 7  1996 MACKCC-L    36  1.47 
 8  1996 MACKOG-L    32  1.16 
 9  1997 MACKCC-L    53  0.755
10  1997 MACKOG-L    37  0.865
# ℹ 44 more rows</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Calculate the mean(λ) and sd(λ) for the two reaches using your calculation from Q1.4. Remember to use the geometric mean and its standard deviation (1 pt).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>g <span class="ot">=</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sitecode) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">Gmean</span>(lambda, <span class="at">na.rm =</span> T),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">test =</span> <span class="fu">exp</span>(<span class="fu">mean</span>(<span class="fu">log</span>(lambda), <span class="at">na.rm =</span>T)),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">Gsd</span>(lambda, <span class="at">na.rm =</span> T))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  sitecode  mean  test    sd
  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 MACKCC-L  1.01  1.01  1.56
2 MACKOG-L  1.03  1.03  1.66</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Using ggplot, plot the lambda for each year. Add a horizontal line for the mean(λ) calculated in question 5 and ribbon around the line to indicate the sd(λ) (3 pt).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="fu">left_join</span>(df, g, <span class="at">by =</span> <span class="st">'sitecode'</span>) <span class="sc">|&gt;</span> <span class="fu">drop_na</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(year, lambda, <span class="at">color =</span> sitecode))<span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean<span class="sc">-</span>sd, <span class="at">ymax =</span> mean<span class="sc">+</span>sd), <span class="at">alpha =</span> <span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">data =</span> g, <span class="fu">aes</span>(<span class="at">yintercept =</span> mean, <span class="at">color =</span> sitecode))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="section-2-23-pts" class="level3">
<h3 class="anchored" data-anchor-id="section-2-23-pts">Section 2 (23 pts)</h3>
<ol type="1">
<li>Using the same dataset from Section 1, estimate <span class="math inline">\(K\)</span> from your <span class="math inline">\(\lambda\)</span> and abundance estimates for both reaches (3 pts). Hint: Remember the linear relationship between density and per-capita growth rate in the density-dependent model discussed in class and the workshop.</li>
</ol>
<p><span class="math inline">\(K_{cc}\)</span> = 95 and <span class="math inline">\(K_{og}\)</span> = 63</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sitecode) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">per.capita =</span> (<span class="fu">lead</span>(Nt)<span class="sc">-</span>Nt)<span class="sc">/</span>Nt)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(Nt, per.capita, <span class="at">color =</span> sitecode)) <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">expression</span>(<span class="fu">italic</span>(N[t])),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span>  <span class="fu">expression</span>(<span class="st">'per capita growth ('</span><span class="sc">~</span><span class="fu">italic</span>(Delta<span class="sc">~</span>N[t]<span class="sc">/</span>N[t])<span class="sc">~</span><span class="st">')'</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">'Per Capita Growth'</span>)<span class="sc">+</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>lcc<span class="ot">=</span> <span class="fu">lm</span>(per.capita <span class="sc">~</span> Nt, <span class="at">data =</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sitecode <span class="sc">==</span> <span class="st">'MACKCC-L'</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lcc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = per.capita ~ Nt, data = df %&gt;% filter(sitecode == 
    "MACKCC-L"))

Residuals:
     Min       1Q   Median       3Q      Max 
-0.68920 -0.24592 -0.07789  0.21188  1.09486 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  0.541209   0.197156   2.745   0.0113 *
Nt          -0.005675   0.002320  -2.446   0.0222 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4308 on 24 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1995,    Adjusted R-squared:  0.1662 
F-statistic: 5.982 on 1 and 24 DF,  p-value: 0.02216</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>Kcc <span class="ot">=</span> <span class="sc">-</span>lcc<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">/</span>lcc<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>log<span class="ot">=</span> <span class="fu">lm</span>(per.capita <span class="sc">~</span> Nt, <span class="at">data =</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sitecode <span class="sc">==</span> <span class="st">'MACKOG-L'</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = per.capita ~ Nt, data = df %&gt;% filter(sitecode == 
    "MACKOG-L"))

Residuals:
    Min      1Q  Median      3Q     Max 
-0.6420 -0.3238 -0.1422  0.2878  1.8807 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  0.991049   0.277543   3.571  0.00155 **
Nt          -0.015790   0.004895  -3.226  0.00361 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5438 on 24 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.3024,    Adjusted R-squared:  0.2734 
F-statistic: 10.41 on 1 and 24 DF,  p-value: 0.003608</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>Kog <span class="ot">=</span> <span class="sc">-</span>log<span class="sc">$</span>coefficients[<span class="dv">1</span>]<span class="sc">/</span>log<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>Kcc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   95.36529 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>Kog</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   62.76384 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Using a discrete density-dependent growth model, project the population growth for salamander in both reaches to 150 years based on the carrying capacity values estimated in Q2 and a starting population size of 50 individuals. Hint: <span class="math inline">\(1 + r_d = \lambda\)</span>; See Gotelli pages 35-37 and pages Stevens 62-68 (3 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>site <span class="ot">=</span> <span class="fu">unique</span>(df<span class="sc">$</span>sitecode)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>N0 <span class="ot">=</span> <span class="dv">50</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>years <span class="ot">=</span> <span class="dv">150</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>pop <span class="ot">=</span> <span class="fu">tibble</span>(<span class="at">time =</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span>years, <span class="at">times =</span> <span class="fu">length</span>(site)),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">Nt =</span> <span class="cn">NA</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">site =</span> <span class="fu">rep</span>(site, <span class="at">each =</span> years<span class="sc">+</span><span class="dv">1</span>)) </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>pop<span class="sc">$</span>Nt[pop<span class="sc">$</span>time <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">=</span> N0</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>rdcc <span class="ot">=</span> g<span class="sc">$</span>mean[g<span class="sc">$</span>sitecode <span class="sc">==</span> <span class="st">'MACKCC-L'</span>] <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>rdog <span class="ot">=</span> g<span class="sc">$</span>mean[g<span class="sc">$</span>sitecode <span class="sc">==</span> <span class="st">'MACKOG-L'</span>] <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(pop<span class="sc">$</span>time)){</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(pop<span class="sc">$</span>time[i] <span class="sc">!=</span> <span class="dv">0</span>){</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(pop<span class="sc">$</span>site[i] <span class="sc">==</span> <span class="st">'MACKCC-L'</span>){</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>      pop<span class="sc">$</span>Nt[i] <span class="ot">=</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]  <span class="sc">+</span> rdcc<span class="sc">*</span>pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>] <span class="sc">/</span> Kcc)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    }<span class="cf">else</span> <span class="cf">if</span>(pop<span class="sc">$</span>site[i] <span class="sc">==</span> <span class="st">'MACKOG-L'</span>){</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>      pop<span class="sc">$</span>Nt[i] <span class="ot">=</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]  <span class="sc">+</span> rdog<span class="sc">*</span>pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>] <span class="sc">/</span> Kog)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>pop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 302 × 3
    time    Nt site    
   &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;   
 1     0  50   MACKCC-L
 2     1  50.2 MACKCC-L
 3     2  50.5 MACKCC-L
 4     3  50.7 MACKCC-L
 5     4  50.9 MACKCC-L
 6     5  51.1 MACKCC-L
 7     6  51.3 MACKCC-L
 8     7  51.6 MACKCC-L
 9     8  51.8 MACKCC-L
10     9  52.0 MACKCC-L
# ℹ 292 more rows</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Using ggplot, plot the population projections for each reach (1 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pop, <span class="fu">aes</span>(time, Nt, <span class="at">color =</span> site))<span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Time'</span>, <span class="at">y =</span> <span class="fu">expression</span>(<span class="fu">italic</span>(N[t])))<span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="4" type="1">
<li>Short essay question: How do the projections for each reach differ? Did the population get as far as the carrying capacity? Why or why not? If not, how many years are required to reach the carrying capacity? When at carrying capacity, do the population fluctuate around K? Why or Why not? (5 pts)</li>
</ol>
<p><em>The population in the old growth forest has a lower carying capacity than the clear cut and approaches carrying capacity around 100 years. The populations do not fluctuate because r is low.</em></p>
<ol start="5" type="1">
<li><p>Project the population of salamander in the two reaches for 150 years using a discrete density-dependent model with environmental stochasticity. Run the projections 50 times for each reach (i.e., 50 projections per reach) (5 pts).<br>
</p>
<ul>
<li>Use the 50 as <span class="math inline">\(N_0\)</span>, carrying capacity (<span class="math inline">\(K\)</span>) values estimated in Q2, and at each time step, use a randomly determined <span class="math inline">\(r_d\)</span> based on the mean and standard deviation of <span class="math inline">\(\lambda\)</span> calculated in Q1.5 – Hint: rtruncnorm() function in R and for loops (e.g., Wickham and Grolemund Chapter 17).</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>){</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  site <span class="ot">=</span> <span class="fu">unique</span>(df<span class="sc">$</span>sitecode)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  N0 <span class="ot">=</span> <span class="dv">50</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  years <span class="ot">=</span> <span class="dv">150</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  pop <span class="ot">=</span> <span class="fu">tibble</span>(<span class="at">time =</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span>years, <span class="at">times =</span> <span class="fu">length</span>(site)),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">Nt =</span> <span class="cn">NA</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">site =</span> <span class="fu">rep</span>(site, <span class="at">each =</span> years<span class="sc">+</span><span class="dv">1</span>),</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">rdcc =</span> <span class="cn">NA</span>,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">rdog =</span> <span class="cn">NA</span>) </span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  pop<span class="sc">$</span>Nt[pop<span class="sc">$</span>time <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">=</span> N0</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(pop<span class="sc">$</span>time)){</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    pop<span class="sc">$</span>rdcc[i] <span class="ot">=</span> truncnorm<span class="sc">::</span><span class="fu">rtruncnorm</span>(<span class="dv">1</span>, <span class="at">a =</span> <span class="dv">0</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">mean =</span> g<span class="sc">$</span>mean[g<span class="sc">$</span>sitecode <span class="sc">==</span> <span class="st">'MACKCC-L'</span>], </span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">sd =</span> g<span class="sc">$</span>sd[g<span class="sc">$</span>sitecode <span class="sc">==</span> <span class="st">'MACKCC-L'</span>]) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    pop<span class="sc">$</span>rdog[i] <span class="ot">=</span> truncnorm<span class="sc">::</span><span class="fu">rtruncnorm</span>(<span class="dv">1</span>, <span class="at">a =</span> <span class="dv">0</span>,</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">mean =</span> g<span class="sc">$</span>mean[g<span class="sc">$</span>sitecode <span class="sc">==</span> <span class="st">'MACKOG-L'</span>], </span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">sd =</span> g<span class="sc">$</span>sd[g<span class="sc">$</span>sitecode <span class="sc">==</span> <span class="st">'MACKOG-L'</span>]) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(pop<span class="sc">$</span>time[i] <span class="sc">!=</span> <span class="dv">0</span>){</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span>(pop<span class="sc">$</span>site[i] <span class="sc">==</span> <span class="st">'MACKCC-L'</span>){</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>        pop<span class="sc">$</span>Nt[i] <span class="ot">=</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]  <span class="sc">+</span> pop<span class="sc">$</span>rdcc[i<span class="dv">-1</span>]<span class="sc">*</span>pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>] <span class="sc">/</span> Kcc)</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>      }<span class="cf">else</span> <span class="cf">if</span>(pop<span class="sc">$</span>site[i] <span class="sc">==</span> <span class="st">'MACKOG-L'</span>){</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>        pop<span class="sc">$</span>Nt[i] <span class="ot">=</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]  <span class="sc">+</span> pop<span class="sc">$</span>rdog[i<span class="dv">-1</span>]<span class="sc">*</span>pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>]<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> pop<span class="sc">$</span>Nt[i <span class="sc">-</span> <span class="dv">1</span>] <span class="sc">/</span> Kog)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>  pop<span class="sc">$</span>rep <span class="ot">=</span> j</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(j <span class="sc">==</span> <span class="dv">1</span>){</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>    pop_all <span class="ot">=</span> pop</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>  }<span class="cf">else</span>{</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>    pop_all <span class="ot">=</span> <span class="fu">bind_rows</span>(pop_all, pop)</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="6" type="1">
<li>Using ggplot, plot a histogram (or density plot) of the population size after 150 year for each reach with a vertical line of the carrying capacity (1 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>p150 <span class="ot">=</span> pop_all <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time <span class="sc">==</span> <span class="dv">150</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(p150, <span class="fu">aes</span>(<span class="at">x =</span> Nt, <span class="at">fill =</span> site))<span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="7" type="1">
<li>Short essay question: How does the population size at time 150 compare between each reach? How do the estimates relate to the carrying capacity? (5 pts).</li>
</ol>
<p><em>They both always reached carrying capacity</em></p>
</section>
<section id="section-3-19-pts" class="level3">
<h3 class="anchored" data-anchor-id="section-3-19-pts">Section 3 (19 pts)</h3>
<p><img src="insect_model.png" class="img-fluid"></p>
<ol type="1">
<li>Convert the loop diagram (life cycle graph) above into a projection matrix (1 pt).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">100</span>,<span class="fl">0.1</span>,<span class="fl">0.5</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.3</span>,<span class="fl">0.2</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> T)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]  [,3]
[1,]  0.0  0.0 100.0
[2,]  0.1  0.5   0.0
[3,]  0.0  0.3   0.2</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Create a starting population vector based on the life stages of this insect species: egg (N = 0), larvae (N = 30), adult (N = 10). Project the population up to 50 years using the starting population vector and the projection matrix you created (hint: A%*%n(t); See Stevens Chapter 2 pages 34-40) (5 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(popbio)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">c</span>(<span class="at">egg =</span> <span class="dv">0</span>, <span class="at">larvae =</span> <span class="dv">30</span>, <span class="at">adult =</span> <span class="dv">10</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>pop <span class="ot">=</span> <span class="fu">pop.projection</span>(A, n, <span class="dv">50</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>pop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$lambda
[1] 1.690573

$stable.stage
[1] 0.90834819 0.07629571 0.01535610

$stage.vectors
      0    1      2      3        4         5         6          7          8
[1,]  0 1000 1100.0 670.00 3359.000 5584.3000 5583.1100 13426.7470 25593.3119
[2,] 30   15  107.5 163.75  148.875  410.3375  763.5988   940.1104  1812.7299
[3,] 10   11    6.7  33.59   55.843   55.8311  134.2675   255.9331   333.2197
              9        10         11        12         13         14        15
[1,] 33321.9736 61046.291 116180.142 175187.39 294152.034 536928.111 871996.65
[2,]  3465.6961  5065.045   8637.152  15936.59  25487.034  42158.720  74772.17
[3,]   610.4629  1161.801   1751.874   2941.52   5369.281   8719.966  14391.61
             16         17         18        19         20         21       22
[1,] 1439160.94 2530997.33 4243771.98 7035023.5 12093131.2 20493005.5 34240861
[2,]  124585.75  206208.97  356204.22  602479.3  1004742.0  1711684.1  2905143
[3,]   25309.97   42437.72   70350.23  120931.3   204930.1   342408.6   581987
             23       24        25        26        27        28         29
[1,] 58198696.0 98794017 166058526 280957654 476446558 803592403 1357742990
[2,]  4876657.4  8258198  14008501  23610103  39900817  67595064  114156772
[3,]   987940.2  1660585   2809577   4764466   8035924  13577430   22994005
             30         31         32          33          34          35
[1,] 2299400526 3884583279 6562497213 11103491299 18769944026 31716103326
[2,]  192852685  326366395  551641526   932070484  1576384372  2665186589
[3,]   38845833   65624972  111034913   187699440   317161033   536347518
              36          37           38           39           40
[1,] 53634751823 90682548022 153262618411 259119833553 438105265711
[2,]  4504203627  7615576996  12876043300  21764283491  36794125101
[3,]   906825480  1532626184   2591198336   4381052657   7405495579
               41           42           43           44           45
[1,] 740549557874 1.251934e+12 2.116614e+12 3.578085e+12 6.048799e+12
[2,]  62207589122 1.051588e+11 1.777727e+11 3.005478e+11 5.080824e+11
[3,]  12519336646 2.116614e+10 3.578085e+10 6.048799e+10 1.022619e+11
               46           47           48           49
[1,] 1.022619e+13 1.728771e+13 2.922518e+13 4.940744e+13
[2,] 8.589212e+11 1.452080e+12 2.454811e+12 4.149923e+12
[3,] 1.728771e+11 2.922518e+11 4.940744e+11 8.352582e+11

$pop.sizes
 [1] 4.000000e+01 1.026000e+03 1.214200e+03 8.673400e+02 3.563718e+03
 [6] 6.050469e+03 6.480976e+03 1.462279e+04 2.773926e+04 3.739813e+04
[11] 6.727314e+04 1.265692e+05 1.940655e+05 3.250083e+05 5.878068e+05
[16] 9.611604e+05 1.589057e+06 2.779644e+06 4.670326e+06 7.758434e+06
[21] 1.330280e+07 2.254710e+07 3.772799e+07 6.406329e+07 1.087128e+08
[26] 1.828766e+08 3.093322e+08 5.243833e+08 8.847649e+08 1.494894e+09
[31] 2.531099e+09 4.276575e+09 7.225174e+09 1.222326e+10 2.066349e+10
[36] 3.491764e+10 5.904578e+10 9.983075e+10 1.687299e+11 2.852652e+11
[41] 4.823049e+11 8.152765e+11 1.378259e+12 2.330168e+12 3.939121e+12
[46] 6.659144e+12 1.125799e+13 1.903204e+13 3.217406e+13 5.439262e+13

$pop.changes
 [1] 25.6500000  1.1834308  0.7143304  4.1087901  1.6977967  1.0711528
 [7]  2.2562636  1.8969882  1.3482022  1.7988368  1.8814221  1.5332763
[13]  1.6747353  1.8085898  1.6351639  1.6532689  1.7492416  1.6801887
[19]  1.6612188  1.7146248  1.6949133  1.6732970  1.6980309  1.6969593
[25]  1.6821994  1.6914806  1.6952107  1.6872484  1.6895943  1.6931632
[31]  1.6896117  1.6894768  1.6917602  1.6905054  1.6898229  1.6910016
[37]  1.6907347  1.6901592  1.6906620  1.6907248  1.6903757  1.6905413
[43]  1.6906610  1.6904881  1.6905151  1.6906066  1.6905362  1.6905206
[49]  1.6905735</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Plot your results using ggplot, popbio, or base R plotting functions. Plot the projection for each stage class (2 pts).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">=</span> <span class="fu">tibble</span>(<span class="at">time =</span> <span class="fu">as.numeric</span>(<span class="fu">colnames</span>(pop<span class="sc">$</span>stage.vectors)),</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">egg =</span> pop<span class="sc">$</span>stage.vectors[<span class="dv">1</span>,],</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">larvae =</span> pop<span class="sc">$</span>stage.vectors[<span class="dv">2</span>,],</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">adult =</span> pop<span class="sc">$</span>stage.vectors[<span class="dv">3</span>,],</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">total =</span> pop<span class="sc">$</span>pop.sizes) <span class="sc">%&gt;%</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(egg<span class="sc">:</span>total, <span class="at">names_to =</span> <span class="st">'stage'</span>, <span class="at">values_to =</span> <span class="st">'n'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">stage =</span> <span class="fu">factor</span>(stage, </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">levels =</span><span class="fu">c</span>(<span class="st">'total'</span>,<span class="st">'egg'</span>,<span class="st">'larve'</span>,<span class="st">'adult'</span>)))</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pp, <span class="fu">aes</span>(time, n, <span class="at">color =</span> stage)) <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Time'</span>, <span class="at">y =</span> <span class="st">'Population size'</span>, <span class="at">color =</span> <span class="st">'Stage'</span>) <span class="sc">+</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">'black'</span>, <span class="st">'brown'</span>, <span class="st">'green'</span>, <span class="st">'pink'</span>))<span class="sc">+</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stage.vector.plot</span>(pop<span class="sc">$</span>stage.vectors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Key_hw2_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="4" type="1">
<li><p>Short essay question: Looking at the plot from Q3, did the population projection reach a stable stage distribution? Why or why not? What could you tell about the fate of the population after 50 years? (5 pts). <em>Yes, because the proportion in each stage remains the same.</em></p></li>
<li><p>Based on the project matrix above, calculate lambda and calculate the stable stage distribution (1 pt).</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>pop<span class="sc">$</span>lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.690573</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>pop<span class="sc">$</span>stable.stage</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.90834819 0.07629571 0.01535610</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Short essay question: What is the proportion between the stages at SSD? What stage is the dominant stage of the population after the stable stage distribution is reached? Why? (5 pts). <em>egg = 0.90834819, larvae = 0.07629571, and adult = 0.01535610. Egg is dominant</em></li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>